const SET_DOCTORS_LIST = 'DoctorTypes@SET_DOCTORS_LIST';
const SET_SELECTED_DOCTOR = 'DoctorTypes@SET_SELECTED_DOCTOR';
const STATUS = 'DoctorTypes@STATUS'

export {
    SET_DOCTORS_LIST,
    SET_SELECTED_DOCTOR,
    STATUS
}